_target_: opr.models.place_recognition.base.SemanticModel

backbone:
  _target_: opr.modules.feature_extractors.ConvNeXtTinyFeatureExtractor
  in_channels: 1
  pretrained: False
head:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: opr.modules.GeM
    - _target_: torch.nn.Linear
      in_features: 768
      out_features: 256
