_target_: opr.models.place_recognition.base.LateFusionModel

image_module:
  _target_: opr.models.place_recognition.ResNet18
  in_channels: 3
  out_channels: 128
  num_top_down: 0
  pooling: gem

cloud_module:
  _target_: opr.models.place_recognition.MinkLoc3D
  in_channels: 1
  out_channels: 128
  num_top_down: 1
  conv0_kernel_size: 5
  block: ECABasicBlock
  layers: [1, 1, 1]
  planes: [32, 64, 64]
  pooling: gem

fusion_module:
  _target_: opr.modules.Concat
