defaults:
  - _self_
  - dataset: nclt/lidar
  - sampler: batch_sampler
  - model: lidar
  - loss: batch_hard_triplet_margin
  - optimizer: adam
  - scheduler: multi_step

wandb:
  disabled: false
  project: CVPR2024

debug: false
device: cuda
seed: 3121999
num_workers: 4

exp_name: ???

epochs: 80
batch_expansion_threshold: 0.7
